pydhi/dfs1.py
pydhi/dfs2.py

Providing default values helps to get started with creating a dfs2 file. Some of the default values makes sense, whereas some are just helpful to get started. E.g. using now() as a default value for the starttime is probably not so useful for real work..

Default values

---

tests/test_dfs1.py
tests/test_dfs2.py

test_write() for dfs1 and dfs2

---

mikeio/dfs0.py

PR not to master but to open PR #81 PR81

Fix exception handling according to previous code

---

mikeio/dfsu.py
tests/test_dfsu.py

Most changes, introduced by auto-format
For the actual change, scroll down to line 1400

Option to read single precision. Closes #40

---

mikeio/dfsu.py
tests/test_dfsu.py

fix get_layer_elements and more plotting

---

mikeio/custom_exceptions.py
mikeio/dfs0.py
mikeio/dfs1.py
tests/test_dfs1.py

Custom exceptions is good practice in python.
Should be used to streamline exception messages and error handling across the code.
Exceptions must also be tested.
Only implemented in dfs1 in this PR.

Use custom exceptions in dfs1

---

mikeio/custom_exceptions.py
mikeio/dfs.py
mikeio/eum.py
mikeio/helpers.py
tests/test_dfs2.py
tests/test_helpers.py

* Add input argument to specify DataValueType, with same default value as previously set automatically,, (http://doc.mikepoweredbydhi.help/webhelp/2019/DHI_DFS/html/T_DHI_Generic_MikeZero_DFS_DataValueType.htm#!) to ItemInfo
* Update reading and writing of header to take DataValueType into account

Read write data value type

---

mikeio/pfs.py
tests/test_pfs.py
tests/testdata/lake.m21fm

Reading PFS with comments

---

README.md

Updated `README.md` to include the conda-forge badge and installation instructions for anaconda.

Readme conda

---

mikeio/dfs.py
mikeio/dfsu.py
mikeio/generic.py
setup.py

I think we should add progress bars to all potentially long-running methods.
This is how it looks like:

Progress bar

---

mikeio/dfs.py
mikeio/dfs0.py
mikeio/dfsu.py
tests/test_dfs0.py

Read slice of noneq calendar. Closes #149

---

mikeio/dfsu.py
tests/test_dfsu.py

Regarding this comments
https://github.com/DHI/mikeio/issues/165#issuecomment-758227869
I just found what the problem is.

Fix the issue with find_nearest_elements by layer number

---

mikeio/dfs0.py
tests/test_dfs0.py

Dataframe has a `to_dfs0` method.
Nice to have it on a pandas series as well.

Pandas Series to dfs0 (similar to the one for DataFrame)

---

mikeio/__init__.py
mikeio/dfsu.py
setup.py
tests/conftest.py
tests/test_dfsu.py

By @georgebv  with minor changes

Dfsu to dfs2

---

mikeio/dataset.py
tests/test_dataset.py

* Create new dataset with list of EUMType in addition to list of ItemInfo
* Accept dataset as argument to interp_time, as a convenience

Dataset convenience

---

mikeio/dfsu.py
tests/test_dfsu.py

Construct a dfsu 2d file with a surface elevation item, based on zn node coordinates of dfsu 3d file.

new method extract_surface_from_3d

---

mikeio/dfs0.py
setup.py
tests/test_dfs0.py

The use of MIKE core backend inspires to do some changes to optimize performance for read/write large dfs0

Using mikecore Dfs0Util

---

mikeio/dfsu.py
tests/test_dfsu.py

extract_track: check for time overlap, fix EOF check

fix extract_track() index bug

---

.gitignore
README.md
docs/getting_started.rst
docs/index.rst
docs/understanding_dataset.rst
mikeio/dataset.py
mikeio/dfsu.py
notebooks/Aggregator.ipynb
notebooks/Dfs0 - Relative time.ipynb
notebooks/Dfs0 - Timeseries.ipynb
notebooks/Dfs1 - Read.ipynb
notebooks/Dfs2 - Boundary.ipynb
notebooks/Dfsu - 2D interpolation.ipynb
notebooks/Dfsu - 3D sigma-z.ipynb
notebooks/Dfsu - Export to netcdf.ipynb
notebooks/Dfsu - Read.ipynb
notebooks/Dfsu - Speed and direction.ipynb
notebooks/Dfsu and Mesh - Plotting.ipynb
notebooks/Generic.ipynb
notebooks/Time interpolation.ipynb

More pages on documentation site including getting-started page. Better and more elaborate docstrings with examples.

Improved documentation

---

mikeio/pfs.py
tests/test_pfs.py
tests/testdata/OresundHD2D_EnKF10.m21fm

Use default encoding "cp1252" like MIKE Core

Fix pfs file character encoding problems on linux

---

docs/understanding_dataset.rst
mikeio/dataset.py
tests/test_dataset.py

Allow basic math operations +, - and * on Datasets. Both with scalar and other Datasets.

Dataset math operations

---

docs/getting_started.rst
docs/understanding_dataset.rst

More pages on documentation site including getting-started page. Better and more elaborate docstrings with examples.

Improved documentation - take 3

---

mikeio/dataset.py
notebooks/Dfsu - Read.ipynb
tests/test_dataset.py

Give the Dataset a describe() method similar to DataFrame

Dataset describe()

---

mikeio/dataset.py
tests/test_dataset.py

- Dataset should support assignment
- Dataset item assignment. Closes #237

dataset item assignment

---

mikeio/dfsu.py

In MIKEcore DfsuFile does not have a EumQuantity attribute. Writing a new mesh from a dfsu file therefore failed. This PR fixes this.

Bugfix: dfsu as mesh with write 

---

mikeio/dataset.py

reduce load time

---

mikeio/dataarray.py
mikeio/dataset.py
tests/test_dataarray.py
tests/test_dataset.py

```
da.isel(y=0)
```
compared to 
```
da.isel(0,axis="y")
```

Isel keywords

---

mikeio/dataarray.py
mikeio/dataset.py
mikeio/spatial/FM_geometry.py
tests/test_dataarray.py
tests/test_dfsu.py

TODO 
* accept DataArray and Dataset as arguments
* interp_time

Datarray/Dataset interp_like

---

mikeio/dataarray.py
tests/test_dataarray.py

DataArray describe() method to be consistent with Dataset describe(). Add describe tests also. 
Tests

DataArray describe() method

---

mikeio/dataarray.py
mikeio/dataset.py
mikeio/dfs0.py
mikeio/dfs1.py
mikeio/dfs2.py
mikeio/dfsu.py
mikeio/spatial/FM_geometry.py
mikeio/spatial/geometry.py
mikeio/spatial/grid_geometry.py
tests/test_dataarray.py
tests/test_dfs1.py
tests/test_dfs2.py

Also, fix missing item in DataArray squeeze() method.

Improve string representation of DataArray/Dataset

---

mikeio/dataset.py
tests/test_dataset.py
tests/test_dfs2.py

add geometry to the combined dataset, otherwise _to_dfs() method with throw error, as it looks for geometry.

add geometry when combine datasets

---

mikeio/spatial/grid_geometry.py
tests/test_geometry_grid.py

Grid1D should accept a list of coordinates

Grid{1D,2D} consistency

---

mikeio/data_utils.py
mikeio/spatial/FM_geometry.py
tests/test_dataset.py
tests/test_dfsu.py
tests/test_dfsu_layered.py

Make sure that selecting layer="bottom" in dfs.read() or ds.sel() will return a proper 2d geometry.

dfsu3d bottom layer as dfsu2d

---

mikeio/dfs.py
tests/test_dfs2.py

Fix. Previously, it was not possible to write DataArrays without time axis to file.

Write dfs123 with no time axis

---

mikeio/dataarray.py
mikeio/dataset.py
mikeio/generic.py
tests/test_dataset.py
tests/test_dfs0.py
tests/test_dfs1.py
tests/test_dfs2.py
tests/test_dfs3.py
tests/test_dfsu.py
tests/test_generic.py

- Change some warnings to errors
- Capture some warnings in tests
- Remove some old ways of working

Misc warnings

---

mikeio/dfs1.py
tests/test_dfs1.py

Fix: Add geo info to Grid1D when reading Dfs1

---

mikeio/spatial/FM_geometry.py
tests/test_dfsu_layered.py

Algorithm for finding dfsu3d top_elements after subsetting was missing the last top element. This PR fixes this.

Fix top elements 3d dfsu subset

---

mikeio/dataarray.py
mikeio/spatial/grid_geometry.py
tests/test_dfs2.py

Similar to GeometryFM, Grid2D should have a plotter, so the user can easily da.geometry.plot().

Grid2D plot

---

mikeio/dataarray.py
mikeio/dataset.py
tests/test_consistency.py
tests/test_dataarray.py
tests/test_dataset.py

Please comment if you think this a good or bad idea.

Allow asterisks in item names

---

mikeio/dfs.py
mikeio/dfs0.py
mikeio/dfs1.py
mikeio/dfsu.py
tests/test_dfs0.py
tests/test_dfs1.py
tests/test_dfs2.py
tests/test_dfsu.py

It was often that we only need all the datetimes in the file without reading the entire file or any item. I just add that property

add time property to mikeio.open and add test

---

docs/eum.md
docs/getting-started.md

And EUMType search example added to docs

Link to units notebook removed from docs

---

mikeio/pfs.py
tests/testdata/pfs/simple.pfs

Pfs tab vs spaces

---

.github/workflows/quick_test.yml
mikeio/dfsu.py
mikeio/spatial/FM_utils.py
mikeio/spectral_utils.py
pytest.ini
tests/test_dfsu.py
tests/test_dfsu_plot.py
tests/test_interpolation.py
tests/test_mesh.py

Make it easier to spot **important** warnings

Capture expected warnings

---

tests/test_pfs.py
tests/testdata/pfs/filenames.pfs

no code changes just more testing

test read write of filenames in pfs

---

docs/pfs.md
mikeio/pfs.py
tests/test_pfs.py

Finish Pfs documentation (including better docstrings) to go with release 1.2.

Pfs documentation

---

mikeio/dataset.py
tests/test_dataset.py

When plotting a Dataset the plot() method did not return anything. This PR fixes this.

Fix Dataset plot return 

---

docs/dataarray.md
mikeio/data_utils.py
mikeio/dataarray.py
mikeio/dataset.py
tests/test_dataarray.py
tests/test_dataset.py

Fix isel returns copy of data

---

mikeio/spatial/FM_geometry.py
mikeio/spatial/grid_geometry.py
tests/test_dfsu.py
tests/test_geometry_grid.py

```python
>>> import mikeio
>>> g = mikeio.Grid2D(bbox=[0,0,1,5])
>>> g
<mikeio.Grid2D>
x: [0.05, 0.15, ..., 0.95] (nx=10, dx=0.1)
y: [0.05, 0.15, ..., 4.95] (ny=50, dy=0.1)
projection: NON-UTM
>>> pt = [0.5, 0.5]
>>> pt in g # this is new!
True
>>> g.contains(pt)
array([ True])
```

Point contains pythonic syntax

---

mikeio/spatial/FM_geometry.py

_GeometryFMLayered always has n_layers

---

mikeio/dfsu/dfsu.py
mikeio/generic.py
mikeio/interpolation.py
mikeio/spatial/FM_geometry.py
mikeio/spatial/FM_utils.py

In collaboration with Github Copilot

Docstrings

---

mikeio/pfs/_pfsdocument.py
tests/test_pfs.py

Support CLOB in `read_pfs()`

---

mikeio/dfsu/_dfsu.py
tests/test_dfsu.py

And certainly not with a wrong timestep.

Don't write non-equidistant dfsu

---

mikeio/dataset/_dataset.py

As identified by the recent mypy 1.6

Remove wrong type

---

.github/workflows/docs.yml
pyproject.toml

And use dedicated quarto action, which should fail on syntax errors.

Updated quartodoc version

---

README.md

on readme.md
Quite straight forward

Added download button

---

mikeio/dataset/_data_plot.py
mikeio/dfs/_dfs0.py
mikeio/dfs/_dfs1.py
mikeio/dfs/_dfs2.py
mikeio/dfs/_dfs3.py
mikeio/dfsu/_dfsu.py
mikeio/dfsu/_factory.py
mikeio/dfsu/_layered.py
mikeio/dfsu/_spectral.py
mikeio/eum/_eum.py
mikeio/pfs/_pfssection.py
mikeio/spatial/_FM_geometry.py
mikeio/spatial/_FM_geometry_layered.py
mikeio/spatial/_FM_geometry_spectral.py
mikeio/spatial/_grid_geometry.py

Added missing class level one-line summary docstring.

---

.pre-commit-config.yaml

Add basic pre-commit

---

mikeio/spatial/_utils.py

Type hints seem to <del>change</del> improve in every release of NumPy. Last one released [yesterday](https://pypi.org/project/numpy/2.2.4/).

Fix numpy related type hints

---

mikeio/dataset/_dataset.py
mikeio/dfs/_dfs0.py
tests/test_dfs0.py

Fix bug in Dfs0 read time slice

---

mikeio/dataset/_data_plot.py
mikeio/dataset/_dataarray.py
mikeio/dataset/_dataset.py
mikeio/dfs/_dfs1.py
mikeio/dfs/_dfs2.py
mikeio/dfs/_dfs3.py
mikeio/eum/_eum.py
mikeio/generic.py
mikeio/pfs/_pfsdocument.py
mikeio/pfs/_pfssection.py
mikeio/spatial/_FM_geometry.py
mikeio/spatial/_FM_geometry_layered.py
mikeio/spatial/_FM_geometry_spectral.py
mikeio/spatial/_grid_geometry.py

https://github.com/asottile/pyupgrade

Upgraded syntax

---

mikeio/dfsu/_spectral.py
mikeio/spatial/_FM_geometry.py
mikeio/spatial/_FM_geometry_layered.py
mikeio/spatial/_FM_geometry_spectral.py
mikeio/spatial/_geometry.py
mikeio/spatial/_grid_geometry.py
tests/test_geometry_grid.py

To avoid several of these confusing methods from `GeometryFM2D`

Linespectra inheritance
