pydhi/dfs0.py, pydhi/helpers.py
In Python 3.7, dfs.ItemInfo.Count raised an error that using len instead
fixes so that code reads a dfs0 file successfully.
=> Replace dfs.ItemInfo.Count with len(dfs.ItemInfo)

mikeio/generic.py, tests/test_generic.py
Added functionality to select which items to apply scaling to (add constant, multiply factor) to any type of dfs file.
Item selection can be done with either positional indexing (item_numbers) or named indexing (item_names).
=> Scale selected items

mikeio/dfs0.py
To avoid ugly timesteps like this
Looks nicer.
Is it a reasonable default to round to seconds?
=> Round time on read to dataframe

mikeio/dfsu.py, tests/test_dfsu.py
I added do_contour as an option to dfsu.plot() method. 
It works for both triangular and quadrilateral and flexible mesh. It needs data at the nodes so I wrote a function that produce node based data from the cell centered data using the Pseudo Laplacian interpolation, similar to MeshNodeInterpolation (https://github.com/DHI/DHI.Mesh). Whenever  Pseudo Laplacian fails I used inverse distance for interpolation. 
Please feel free to optimize the code if it is required.
=> Add contour option to dfsu.plot

mikeio/dfsu.py
this line of code is needed 
ax.tripcolor(triang, zn, edgecolors='face', vmin=vmin, vmax=vmax, cmap=cmap)
otherwise if the vmin and vmax do not cover the entire zn range it plots white area. 
with: 
without would be like this!
=> Handle dfsu contour_lines

mikeio/dfs.py, mikeio/dfs1.py, mikeio/dfs2.py, tests/test_dfs2.py
I noticed that you already change the method find_nearest_element in the dfsu to find_nearest_elements so I applied that change to the dfs2 as well. 
Additionally, as per our discussion I modified the code to handle the NonEquidistant  Time axis as well. When I tried to do that I noticed that some of the checking for Equidistant and nonEquidistant  was some of the codes were there before. in The current code both Equidistant and nonEquidistant Time Axis can be created depend on the parameter that is used by user. 
Thanks,
=> Dfs1 and Dfs2 NonEquidistant Time Axis

mikeio/dfsu.py, tests/conftest.py, tests/test_dfsu.py
This PR introduces a new method to the `Dfsu` class - `.to_dfs2`. This method provides an interface to convert `Dfsu` to `Dfs2` with similar functionality to what DHI MIKE has when creating DFS2 files from DFSU files.
=> Exporting Dfsu to Dfs2

mikeio/pfs.py, tests/test_pfs.py
In the current implementation of the PFSCore class (wrapping the MIKE SDK), it tries to cleverly find the type of parameter to use the appropriate method, but in case of ambiguity such as 1.0, which can be interpreted both as integer and float, this goes wrong.
So it can now be explicitly forced to be interpreted as a float.
=> Pfs modify float explicit

mikeio/dfs0.py, tests/test_dfs0.py
* Change how DataValueType is passed for DFS0 to be through ItemInfo list instead of as separate argument to be consistent with other dfs formats
* Respect DataValueType information in DFS0 files when reading with mikeio.read
* close #184
=> Make setting of DataValueType for DFS0 consistent with other methods

mikeio/base.py, mikeio/dataset.py, mikeio/dfs.py, mikeio/dfs0.py, mikeio/dfsu.py
To ensure consistent naming of properties across classes.
Now it is clear that:
- `Dataset`
- `Dfs0`
- `Dfs1`
- `Dfs2`
- `Dfsu`
all have the same properties like  `start_time` and `end_time`.
=> Abstract base class as contract for common props

mikeio/dfs.py, mikeio/dfs0.py, mikeio/dfsu.py
The use of Dfs0Util.ReadDfs0DataDouble() gives problems with rounding errors. 
This can be handled by rounding to milliseconds after converting to DateTimeIndex. This also reduces the need for having to-seconds rounding in to_dataframe() method. 
Furthermore, the previous time conversion with a generator and a list comprehension was found to be slow and has been been replaced by a fast pandas method.
=> Time index fix

setup.py, tests/test_dfsu_plot.py
After release of matplotlib 3.5.0 there is an error on using discrete levels on a contour plot.
Maybe related to: [Matplotlib 3.5 - Colorbars changes](https://matplotlib.org/3.5.0/api/prev_api_changes/api_changes_3.5.0.html#colorbars-now-have-pan-and-zoom-functionality)
=> Discrete colorbar error - matplotlib 3.5.0

mikeio/dfs2.py, mikeio/spatial/grid_geometry.py, tests/test_dataarray.py, tests/test_dfs2.py, tests/test_geometry_Grid2D.py
Creating a Grid2D like this:
```
Grid2D(shape=(10,2),..)
```
is intuitive with `shape=(nx,ny)`, except that it matches poorly with the shape of the data where the `shape=(nt,ny,nx)` 😕 
Thus in the spirit of explicit is better than explicit (and a Grid2D doesn't accept anything else than 2d anyway):
```
Grid2D(nx=10, ny=2,...)
```
=> Grid 2D create with nx, ny

mikeio/__init__.py, mikeio/dfs.py, mikeio/dfs1.py, mikeio/dfs3.py, mikeio/dfsu.py, mikeio/generic.py, tests/test_dfsu.py
Data is typically stored as float32 (single precision). Change default behaviour to read without conversion to float64 unless explicitly requested.
=> Default to float32, and allow float64

mikeio/dataarray.py, mikeio/dataset.py, mikeio/dfs2.py, mikeio/spatial/FM_geometry.py, mikeio/spatial/grid_geometry.py, tests/test_dataarray.py, tests/test_dfs2.py
Things to consider:
* Should we generally use the names j- and k- to refer to the first and second index following MIKE standard? 
* Should the Grid1D node coordinates be public
* polygon in area selection should crop to its bounding box and then making everything outside the polygon np.nan. In that way it would be simple to calculate statistics only over water. 
* What to do with origo and axis in 2dv dfs2 files? They are still common in MIKE3 modelling. TODO: add one as test data
* Remove origo from x0,y0 ? 
* Special class Grid2DRotated()
=> Grid1D and Grid2d subsetting

mikeio/dataset.py, mikeio/dfs0.py, tests/performance/test_performance_dfs0.py
Closes #358 
The overhead of creating DataArrays for every item seems to be too big for Dfs0s with many items (e.g. +1000 items).
=> Fix poor performance of read of many-item-dfs0

mikeio/spatial/FM_geometry.py, tests/test_dfsu_layered.py
Right after releasing v 1.0.2 I found another problem with profiles extracted from DfsuSigma files where number of sigma layers where incorrect and prevented saving them as a new Dfsu file.
=> Save vertical profile from sigma only dfsu 3d

mikeio/spatial/FM_geometry.py, tests/test_dfsu_layered.py
It was previously not possible to write a 3d GeometryFM object to a new mesh file. This PR fixes this. Thanks to @lezhongwen for pointing this out in https://github.com/DHI/mikeio/discussions/391.
=> dfsu3d to_mesh fix

mikeio/dfsu.py, mikeio/dfsu_layered.py, tests/test_dfsu.py, tests/test_dfsu_layered.py
If the area covered only a single element a "strange" error message was given. This PR also provides a better error message if no elements are inside the area. Closing #376.
=> Fix dfsu read single element in area argument

mikeio/dataarray.py, mikeio/spatial/grid_geometry.py, tests/test_geometry_grid.py
Grid2D should have a method that converts it to a GeometryFM
=> Grid2D to GeometryFM

mikeio/dataarray.py, mikeio/dataset.py, tests/test_dataarray.py
Range (max - min) is an intuitive measure of dispersion, but since range already has a different meaning in python and NumPy, Numpy uses the name [ptp](https://numpy.org/doc/stable/reference/generated/numpy.ptp.html) instead which is now available as a method on the DataArray and Dataset classes.
Below is a illustration of range vs standard deviation (another popular measure of dispersion)
=> DataArray/Dataset ptp (range)

mikeio/pfs.py, tests/test_pfs.py, tests/testdata/pfs/nonunique.pfs
Allow the user to select whether he/she wants to allow repeated keywords in the same PfsSection by introducing a new argument in read_pfs() `unique_keywords` by default True. Relevant for MIKE Zero Plot Composer where `unique_keywords` should be set to False. Closes #434 
Fixes also bug with repeated keywords when unique_keywords=True (as it was before).
=> Pfs allow repeated keywords

mikeio/pfs.py, tests/test_pfs.py
MIKE FM does not use repeated keywords. If the same keyword is defined in a section, the first one will be read. MIKE IO should have the same behaviour.
=> Pfs take first of repeated keywords

mikeio/dataset.py, mikeio/generic.py, tests/test_consistency.py, tests/test_dataset.py
modified dataset test to concatenate file with single timestep. When concantenating will result in error in shape check as well as dims check as time dimension is dropped for single timestep datasets and not available for checking.
=> dataset concatenation single timestep

mikeio/dfs0.py, mikeio/dfsutil.py, mikeio/eum.py, tests/test_dfs0.py
@ecomodeller , I often find myself needing to get an overview of the content of dfs files without reading any data. Returning this as a dafarame allows easy export and stacking when looping multiple files. For now I added to dfs0 only and you can do:
```
import mikeio
ds = mikeio.open("testdata/random.dfs0")
ds.items_dataframe
```
Seems like it would have to be added to many places. And maybe it's just a (too) specialized form of `ds.items`?
=> add dfs0 property items_dataframe

mikeio/pfs.py, notebooks/PFS.ipynb, tests/test_pfs.py
Move internal write method to PfsSection such that it can be used for __repr__. This makes sure that the __repr__ etc look exactly like what is written to file. This will also make it easy to write to a stream instead of a file.
=> Pfs refactor write

mikeio/dataarray.py, mikeio/interpolation.py, mikeio/spatial/grid_geometry.py, tests/test_dataarray.py, tests/test_interpolation.py
The spatial information in a Dfs1 file is rarely used.
Thus it makes sense when creating a DataArray with dimensions (time,x) it defaults to a Grid1D where $x \in [0,1]$
=> Create 1d dataset with default grid

mikeio/__init__.py, mikeio/dataarray.py, mikeio/dataset.py, mikeio/dfsu.py, mikeio/dfsu_layered.py, mikeio/dfsutil.py, mikeio/generic.py, tests/test_dataarray.py, tests/test_dataset.py, tests/test_generic.py
Reading a corrupt timestep apparently messes up some internals.
A possible solution could be to close the dfs object and re-open it.
Not sure how to QA this PR☹️ But at least it should it not break any existing functionality.
=> Read corrupt dfs files

mikeio/__init__.py, mikeio/dfsu/__init__.py, pyproject.toml
`FMskill` uses _Dfsu which was removed in v 1.3
This PR adds a new _Dfsu alias in order to avoid errors here:
https://github.com/DHI/fmskill/blob/64a831cc814b0a4074aa9213de69fd7744d11dc0/fmskill/model/dfs.py#L48
=> Add alias for _Dfsu

mikeio/data_utils.py, mikeio/dataset.py, tests/test_data_utils.py
During the big rewrite to v 1.0 where DataArray was introduced, Dataset and DataArray needed many common helper functions which was extracted into a common module data_utils.
Dataset only uses a few of these, which is now clearer.
=> Only import selected functions

mikeio/dfs.py, tests/test_dfs0.py
I get the to me unexpected behavior:
After reading items by name
```
items = ["NotFun", "VarFun01"]
dfs = Dfs0(dfs0file)
dfs.read(items=items) 
```
`items` is no longer equal `["NotFun", "VarFun01"]`
=> Read items by name fix

mikeio/spatial/geometry.py, pyproject.toml, tests/spatial/test_point.py
https://www.ogc.org/standard/sfa/
The Shapely library is the Python wrapper for the GEOS library, which is a standard in geospatial analysis.
At this point we don't want to depend upon the shapely library (and it's dependencies), but if the user has it installed, we can easily convert mikeio points to shapely points.
=> Well Known Text for Points

mikeio/dfs/_dfs2.py, mikeio/dfs/_dfs3.py, tests/test_dfs3.py
Allow specification of dtype for Dfs3.read() (as implemented in Dfs2.read() )
As described in #558
=> Dtype dfs3 read

mikeio/spatial/_geometry.py, tests/test_geometry_grid.py
In the spirit of failing fast, validate that a projection string is acceptable by MIKE on creation of geometry instead on writing to disk.
=> Validate projection string

pyproject.toml
By removing:
* Notebooks
* Tests (testdata)
* Images
From the source distribution that is uploaded to PyPI. The wheel file is already slim.
=> Slim source dist

mikeio/_track.py, mikeio/dataset/_data_utils.py, mikeio/dataset/_dataarray.py, mikeio/dataset/_dataset.py, mikeio/dfs/_dfs.py, mikeio/dfsu/_dfsu.py, mikeio/dfsu/_spectral.py, mikeio/eum/_eum.py, mikeio/generic.py, mikeio/pfs/_pfsdocument.py, mikeio/spatial/_FM_geometry.py, mikeio/spatial/_FM_geometry_layered.py, mikeio/spatial/_grid_geometry.py, mikeio/xyz.py, pyproject.toml, tests/test_dataset.py
This line enables the union type hint syntax from 3.10 to be used in 3.7+
```python
from __future__ import annotations
```
I.e.
We can replace
```python
def foo(Union[int,str]) -> Union[int,bool):
...
```
with the version that is easier to read for humans🙂
```python
def foo(int | str) -> int | bool
...
```
=> Type hints from the future

mikeio/dataset/_dataset.py
In order to make better use of type hints for auto-completion.
Selecting a single item returns a `DataArray`, while selecting multiple items returns a `Dataset`.
Consistent with `xarray`.
=> Overload `Dataset.__getitem__`

mikeio/dataset/_dataarray.py, mikeio/dataset/_dataset.py, mikeio/dfs/_dfs.py, mikeio/dfsu/_dfsu.py, mikeio/dfsu/_layered.py, tests/test_dataset.py
This might cause problems for append workflows #691.
=> Single timestep dataset forgets dt

.vscode/settings.json, mikeio/__init__.py, mikeio/_track.py, mikeio/dataset/_data_plot.py, mikeio/dataset/_dataarray.py, mikeio/dataset/_dataset.py, mikeio/dfs/_dfs3.py, mikeio/dfsu/_dfsu.py, mikeio/dfsu/_layered.py, mikeio/dfsu/_spectral.py, mikeio/eum/_eum.py, mikeio/exceptions.py, mikeio/pfs/_pfsdocument.py, mikeio/pfs/_pfssection.py, mikeio/spatial/_FM_geometry.py, mikeio/spatial/_FM_geometry_layered.py, mikeio/spatial/_FM_geometry_spectral.py, mikeio/spatial/_FM_utils.py, mikeio/spatial/_geometry.py, mikeio/spatial/_utils.py, mikeio/spatial/crs.py, mikeio/xyz.py, mypy.ini, tests/test_geometry_grid.py
A step up in strictness [mypy - disallow_untyped_defs](https://mypy.readthedocs.io/en/stable/config_file.html#confval-disallow_untyped_defs)
=> More type hints - No untyped defs

mikeio/dataset/_dataset.py, mikeio/eum/_eum.py, tests/test_dfs0.py
also changing tests to cover this change and fixing doc typo in _dataset.py
=> Fixing copying of data_value_type in from_pandas

.github/workflows/docs.yml, .github/workflows/downstream_test.yml, .github/workflows/full_test.yml, .github/workflows/legacy_test.yml, .github/workflows/notebooks_test.yml, .github/workflows/perf_test.yml, .github/workflows/python-publish.yml, MANIFEST.in, Makefile, mikeio/__init__.py, pyproject.toml
Only keep the necessary files in the source distribution., (Wheel was already minimal).
=> Slim sdist

.github/workflows/full_test.yml, .github/workflows/python-publish.yml
OS specific functionality is handled by `mikecore`. MIKE IO as an abstraction on top of `mikecore` mainly deals with os-independent functionality. Thus it seems like a waste to run all tests on Windows on each commit. But still important to verify before each release.
=> Only run tests on Windows before each release.

mikeio/__init__.py, pyproject.toml
Enables derived package to use type checkers (e.g. mypy, pyright) to find bugs:
https://typing.readthedocs.io/en/latest/spec/distributing.html#packaging-typed-libraries
```python
import mikeio
def main(ds: mikeio.Dataset):
print(ds.item[0])
```
**Before:**  😢
```bash
$ mypy hello.py
hello.py:1: error: Skipping analyzing "mikeio": module is installed, but missing library stubs or py.typed marker  [import-untyped]
hello.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```
**After:** 😄 
```bash
$ mypy hello.py
hello.py:4: error: "Dataset" has no attribute "item"; maybe "items"?  [attr-defined]
Found 1 error in 1 file (checked 1 source file)
```
=> Indicate that MIKE IO uses type hints

docs/_quarto.yml
[Hybrid navigation](https://quarto.org/docs/websites/website-navigation.html#hybrid-navigation) uses a context aware sidebar.
E.g. navigating to somewhere in the user guide: `/user-guide/*`
or on the api pages: `/api/*`
This pull request includes updates to the `docs/_quarto.yml` file to reorganize the sidebar navigation structure. The changes aim to improve the user experience by making the navigation more intuitive and structured.
Key changes include:
* Added a new "User Guide" section with links to relevant documentation files.
* Reorganized the "Examples" section to include sub-sections for different example types, making it easier to find specific examples.
* Introduced a new "API Reference" section with links to various API documentation files.
* Removed the old sidebar …
=> Documentation: Hybrid navigation

mikeio/dfsu/_dfsu.py, mikeio/spatial/_FM_geometry.py, tests/test_dfsu.py
`Dfsu2DH.read(x=, y=)` can be used to read a number of positions (stations).
Inspired by discussion in #482 
@Hendrik1987 is this good enough, or would you still prefer a `extract_stations` method?
=> Add missing dfsu read x,y test

mikeio/dataset/_dataarray.py, mikeio/dataset/_dataset.py, mikeio/dfs/_dfs0.py, tests/test_consistency.py, tests/test_dataarray.py, tests/test_dfs0.py, tests/test_dfs1.py
Tired of seeing this every time I build the docs, indicating an inconsistency.
```
/home/jan/src/mikeio/mikeio/eum/_eum.py:1414: Parameter 'type' does not appear in the function signature
/home/jan/src/mikeio/mikeio/dataset/_dataarray.py:626: Parameter 'time' does not appear in the function signature
/home/jan/src/mikeio/mikeio/dataset/_dataarray.py:626: Parameter 'x' does not appear in the function signature
/home/jan/src/mikeio/mikeio/dataset/_dataarray.py:626: Parameter 'y' does not appear in the function signature
/home/jan/src/mikeio/mikeio/dataset/_dataarray.py:626: Parameter 'z' does not appear in the function signature
/home/jan/src/mikeio/mikeio/dataset/_dataarray.py:626: Parameter 'element' does not appear in the function signature …
```
=> Use named arguments to isel/sel

docs/user-guide/pfs.qmd, mikeio/pfs/__init__.py, mikeio/pfs/_pfsdocument.py, mikeio/pfs/_pfssection.py, tests/test_pfs.py
E.g. fixing the bug of supporting comments inside quotes. E.g. `foo = '//' `, commonly found in MIKE+ .mupp files.
=> Tweaking pfs

docs/user-guide/dataarray.qmd, docs/user-guide/dataset.qmd, mikeio/dataset/_dataarray.py, mikeio/dataset/_dataset.py, tests/test_dataset.py
* Allow multiplication + division
* Be more permissive, only force shapes of the two datasets to be identical
* Use item info from the first argument (no longer invent new name e.g. "foo * bar")
=> Support multiplication and division of datasets.

mikeio/pfs/_pfssection.py, tests/test_pfs.py
#812 added the ability to access parts of a PfsDocument using a nested path, e.g. 
```python
>>> pfs["foo/bar/baz"]
0
```
This PR extends the functionality to set values using a nested path.
```python
pfs["foo/bar/baz"] = 1
```
=> Pfs set nested path

mikeio/dataset/_dataarray.py, mikeio/dataset/_dataset.py, mikeio/dfs/_dfs0.py, tests/test_dataset.py, tests/test_dfs1.py, tests/test_dfsu3d.py
**Overall Purpose:**  
This PR simplifies the Dataset class and its related logic, focusing on cleaner initialization and removal of deprecated and redundant code. 
**Key Changes:**
- **Dataset Initialization:**
- The Dataset class now only accepts a Mapping or Sequence of DataArrays or a single DataArray. The previous support for initializing with raw numpy arrays is removed.
- The deprecated and more complex multi-overload __init__ signature is replaced with a simpler one.
- **Removal of Deprecated Features:**
- All code related to initializing a Dataset from a list of numpy arrays is removed, including related warnings and overloads.
- Functions and properties like create_empty_data, n_elements (on Dataset), and multi-indexing guards are deleted.
**Impact:**  
These changes modernize …
=> Simplify Dataset
